import AdityaMehra from "@/assets/avatars/AdityaMehra.png";
import CarsonDarrin from "@/assets/avatars/CarsonDarrin.png";
import FranzPerez from "@/assets/avatars/FranzPerez.png";
import NehaKulkarni from "@/assets/avatars/NehaKulkarni.png";
import RohanIyer from "@/assets/avatars/RohanIyer.png";

export const access = [
  {
    key: "1",
    date: "02/04/2025",
    name: "Carson Darrin",
    initials: "CD",
    email: "carson.darrin@apple.com",
    device: "Windows 10 Pro 22H2",
    access: "USB Access",
    avatar: CarsonDarrin,
    deviceName: "Latitude-7420",
    domain: "example.local",
    agentVersion: "1.0.0",
    publicIP: "203.0.113.45",
    privateIP: "192.168.1.101",
    accessDuration: "30 mins",
    reason: "Need to transfer project files",
  },
  {
    key: "2",
    date: "08/04/2025",
    name: "Franz Perez",
    initials: "FP",
    email: "franz.perez@apple.com",
    device: "Windows 10 Home",
    access: "Unblock Downloads",
    avatar: FranzPerez,
    deviceName: "ThinkPad-T14",
    domain: "corp.local",
    agentVersion: "1.2.0",
    publicIP: "198.51.100.22",
    privateIP: "192.168.1.102",
    accessDuration: "1 hour",
    reason: "Required for downloading project dependencies",
  },
  {
    key: "3",
    date: "14/04/2025",
    name: "Aditya Mehra",
    initials: "AM",
    email: "aditya.mehra@apple.com",
    device: "Windows 11 Home",
    access: "Full Administrator Access",
    avatar: AdityaMehra,
    deviceName: "XPS-15",
    domain: "dev.local",
    agentVersion: "1.1.5",
    publicIP: "203.0.113.99",
    privateIP: "192.168.1.110",
    accessDuration: "Until EOD",
    reason: "Debugging system configurations",
  },
  {
    key: "4",
    date: "18/04/2025",
    name: "Neha Kulkarni",
    initials: "NK",
    email: "neha.kulkarni@apple.com",
    device: "Windows 10",
    access: "Webcam Access",
    avatar: NehaKulkarni,
    deviceName: "Inspiron-5406",
    domain: "marketing.local",
    agentVersion: "1.0.8",
    publicIP: "198.51.100.77",
    privateIP: "192.168.1.120",
    accessDuration: "45 mins",
    reason: "Joining a secure remote video call",
  },
  {
    key: "5",
    date: "25/04/2025",
    name: "Rohan Iyer",
    initials: "RI",
    email: "rohan.iyer@apple.com",
    device: "Windows 11 Home",
    access: "USB Access",
    avatar: RohanIyer,
    deviceName: "EliteBook-840",
    domain: "finance.local",
    agentVersion: "1.3.2",
    publicIP: "203.0.113.200",
    privateIP: "192.168.1.130",
    accessDuration: "15 mins",
    reason: "Copying financial reports to secure drive",
  },
];
