export const alerts = [
  {
    key: "1",
    date: "02/04/2025",
    name: "Carson Darrin",
    initials: "JD",
    email: "carson.darrin@apple.com",
    category: "Data Leakage",
    description: "Confidential Content Copied",
    status: "Resolved",
  },
  {
    key: "2",
    date: "05/04/2025",
    name: "Franz Perez",
    initials: "FP",
    email: "franz.perez@apple.com",
    category: "File Integrity",
    description: "Multiple Login Attempts",
    status: "Unresolved",
  },
  {
    key: "3",
    date: "14/04/2025",
    name: "Aditya Mehra",
    initials: "AP",
    email: "aditya.mehra@apple.com",
    category: "Authentication",
    description: "Suspicious File Activity Detected",
    status: "Unresolved",
  },
  {
    key: "4",
    date: "17/04/2025",
    name: "Neha Kulkarni",
    initials: "NK",
    email: "neha.kulkarni@apple.com",
    category: "Access Violation",
    description: "Malware Signature match found",
    status: "Resolved",
  },
  {
    key: "5",
    date: "24/04/2025",
    name: "Rohan Iyer",
    initials: "RI",
    email: "rohan.iyer@apple.com",
    category: "Authentication",
    description: "Unauthorised USB access",
    status: "Unresolved",
  },
];
