import AdityaMehra from "@/assets/avatars/AdityaMehra.png";
import CarsonDarrin from "@/assets/avatars/CarsonDarrin.png";
import FranzPerez from "@/assets/avatars/FranzPerez.png";
import NehaKulkarni from "@/assets/avatars/NehaKulkarni.png";
import RohanIyer from "@/assets/avatars/RohanIyer.png";

export const alerts = [
  {
    key: "1",
    date: "02/04/2025",
    name: "Carson Darrin",
    initials: "CD",
    email: "carson.darrin@apple.com",
    category: "Data Leakage",
    description: "Confidential Content Copied",
    status: "Resolved",
    avatar: CarsonDarrin,
    // 🔹 Modal Data
    os: "Windows 10 Pro 22H2",
    loggedIn: "carson",
    deviceName: "Latitude-7420",
    domain: "example.local",
    agentVersion: "1.0.0",
    publicIP: "203.0.113.45",
    privateIP: "192.168.1.101",
    alertType: "Data Exfiltration",
    severity: "High",
    alertCategory: "Confidential File Transfer",
    alertDescription: "Sensitive PDF copied to an external USB drive.",
    asset: "Laptop - 1234",
    network: "10.10.4.23 → 198.51.100.9",
  },
  {
    key: "2",
    date: "05/04/2025",
    name: "Franz Perez",
    initials: "FP",
    email: "franz.perez@apple.com",
    category: "File Integrity",
    description: "Multiple Login Attempts",
    status: "Unresolved",
    avatar: FranzPerez,
    os: "Windows 11 Pro",
    loggedIn: "franz",
    deviceName: "ThinkPad-T14",
    domain: "corp.local",
    agentVersion: "1.2.3",
    publicIP: "203.0.113.88",
    privateIP: "192.168.1.102",
    alertType: "Brute Force",
    severity: "Medium",
    alertCategory: "Authentication Failures",
    alertDescription: "Multiple failed login attempts detected from remote IP.",
    asset: "Desktop - 4567",
    network: "10.10.5.20 → 198.51.100.20",
  },
  {
    key: "3",
    date: "14/04/2025",
    name: "Aditya Mehra",
    initials: "AM",
    email: "aditya.mehra@apple.com",
    category: "Authentication",
    description: "Suspicious File Activity Detected",
    status: "Unresolved",
    avatar: AdityaMehra,
    os: "macOS Ventura 13.2",
    loggedIn: "aditya",
    deviceName: "MacBookPro-16",
    domain: "example.corp",
    agentVersion: "2.0.1",
    publicIP: "203.0.113.120",
    privateIP: "192.168.1.103",
    alertType: "File Tampering",
    severity: "High",
    alertCategory: "Suspicious File Modification",
    alertDescription: "System file `/etc/passwd` was modified unexpectedly.",
    asset: "MacBook - 8901",
    network: "10.10.6.40 → 198.51.100.33",
  },
  {
    key: "4",
    date: "17/04/2025",
    name: "Neha Kulkarni",
    initials: "NK",
    email: "neha.kulkarni@apple.com",
    category: "Access Violation",
    description: "Malware Signature match found",
    status: "Resolved",
    avatar: NehaKulkarni,
    os: "Ubuntu 22.04 LTS",
    loggedIn: "neha",
    deviceName: "Dell-XPS-15",
    domain: "security.lab",
    agentVersion: "3.1.4",
    publicIP: "203.0.113.77",
    privateIP: "192.168.1.104",
    alertType: "Malware",
    severity: "High",
    alertCategory: "Malware Trojan Quarantined",
    alertDescription: "Win32/TrojanX detected in `/home/neha/Downloads/invoice.exe`.",
    asset: "Laptop - 5678",
    network: "10.10.7.10 → 198.51.100.44",
  },
  {
    key: "5",
    date: "24/04/2025",
    name: "Rohan Iyer",
    initials: "RI",
    email: "rohan.iyer@apple.com",
    category: "Authentication",
    description: "Unauthorised USB access",
    status: "Unresolved",
    avatar: RohanIyer,
    os: "Windows 11 Enterprise",
    loggedIn: "rohan",
    deviceName: "Surface-Laptop-4",
    domain: "corp.net",
    agentVersion: "2.5.6",
    publicIP: "203.0.113.200",
    privateIP: "192.168.1.105",
    alertType: "USB Access",
    severity: "Low",
    alertCategory: "Unauthorized Peripheral",
    alertDescription: "Unrecognized USB storage device connected.",
    asset: "Laptop - 9999",
    network: "10.10.8.55 → 198.51.100.55",
  },
];
