import AdityaMehra from "@/assets/avatars/AdityaMehra.png";
import CarsonDarrin from "@/assets/avatars/CarsonDarrin.png";
import FranzPerez from "@/assets/avatars/FranzPerez.png";
import NehaKulkarni from "@/assets/avatars/NehaKulkarni.png";
import RohanIyer from "@/assets/avatars/RohanIyer.png";

export const connections = [
  {
    key: "1",
    date: "02/04/2025",
    name: "Carson Darrin",
    initials: "CD",
    email: "carson.darrin@apple.com",
    device: "Windows 10 Pro",
    agentVersion: "1.0.0",
    avatar: CarsonDarrin,
    details: {
      os: "Windows 10 Pro 22H2",
      loggedIn: "delluser",
      deviceName: "DESKTOP-01A2B3C",
      domain: "WorkGroup",
      manufacturer: "Dell Inc.",
      publicIP: "203.0.113.45",
      privateIP: "192.168.1.101",
      hardware: {
        cpu: {
          name: "Intel(R) Core(TM) i7-10750H",
          manufacturer: "Intel",
          speed: "2.60 GHz",
          cores: 6,
        },
        gpu: {
          name: "NVIDIA GeForce GTX 1660 Ti",
          manufacturer: "NVIDIA",
          capacity: "6 GB",
        },
        memory: {
          name: "Corsair Vengeance LPX DDR4",
          manufacturer: "Corsair",
          speed: "3000 MHz",
          capacity: "16 GB",
        },
        storage: {
          name: "Samsung SSD 970 EVO Plus",
          manufacturer: "Samsung",
          capacity: "512 GB",
        },
      },
    },
  },
  {
    key: "2",
    date: "08/04/2025",
    name: "Franz Perez",
    initials: "FP",
    email: "franz.perez@apple.com",
    device: "Windows 10 Home",
    agentVersion: "1.0.0",
    avatar: FranzPerez,
    details: {
      os: "Windows 10 Home 21H2",
      loggedIn: "franzp",
      deviceName: "LAPTOP-FRZP01",
      domain: "HomeGroup",
      manufacturer: "HP Inc.",
      publicIP: "198.51.100.72",
      privateIP: "192.168.0.110",
      hardware: {
        cpu: {
          name: "Intel(R) Core(TM) i5-10300H",
          manufacturer: "Intel",
          speed: "2.50 GHz",
          cores: 4,
        },
        gpu: {
          name: "Intel UHD Graphics",
          manufacturer: "Intel",
          capacity: "1 GB Shared",
        },
        memory: {
          name: "Kingston DDR4",
          manufacturer: "Kingston",
          speed: "2666 MHz",
          capacity: "8 GB",
        },
        storage: {
          name: "WD Blue SSD",
          manufacturer: "Western Digital",
          capacity: "256 GB",
        },
      },
    },
  },
  {
    key: "3",
    date: "14/04/2025",
    name: "Aditya Mehra",
    initials: "AM",
    email: "aditya.mehra@apple.com",
    device: "Windows 11 Home",
    agentVersion: "1.0.0",
    avatar: AdityaMehra,
    details: {
      os: "Windows 11 Home 23H2",
      loggedIn: "adityam",
      deviceName: "DESKTOP-ADI11",
      domain: "WorkGroup",
      manufacturer: "Lenovo",
      publicIP: "203.0.113.99",
      privateIP: "192.168.1.115",
      hardware: {
        cpu: {
          name: "AMD Ryzen 5 5600H",
          manufacturer: "AMD",
          speed: "3.30 GHz",
          cores: 6,
        },
        gpu: {
          name: "NVIDIA RTX 3050",
          manufacturer: "NVIDIA",
          capacity: "4 GB",
        },
        memory: {
          name: "Crucial DDR4",
          manufacturer: "Micron",
          speed: "3200 MHz",
          capacity: "16 GB",
        },
        storage: {
          name: "Samsung NVMe SSD",
          manufacturer: "Samsung",
          capacity: "1 TB",
        },
      },
    },
  },
  {
    key: "4",
    date: "18/04/2025",
    name: "Neha Kulkarni",
    initials: "NK",
    email: "neha.kulkarni@apple.com",
    device: "Windows 10",
    agentVersion: "1.0.0",
    avatar: NehaKulkarni,
    details: {
      os: "Windows 10 Enterprise 22H2",
      loggedIn: "neha.k",
      deviceName: "WORKSTATION-NK",
      domain: "Corporate",
      manufacturer: "Acer",
      publicIP: "203.0.113.150",
      privateIP: "192.168.10.50",
      hardware: {
        cpu: {
          name: "Intel(R) Core(TM) i7-9700",
          manufacturer: "Intel",
          speed: "3.00 GHz",
          cores: 8,
        },
        gpu: {
          name: "NVIDIA Quadro P1000",
          manufacturer: "NVIDIA",
          capacity: "4 GB",
        },
        memory: {
          name: "Kingston DDR4 ECC",
          manufacturer: "Kingston",
          speed: "2666 MHz",
          capacity: "32 GB",
        },
        storage: {
          name: "Seagate Barracuda HDD",
          manufacturer: "Seagate",
          capacity: "2 TB",
        },
      },
    },
  },
  {
    key: "5",
    date: "25/04/2025",
    name: "Rohan Iyer",
    initials: "RI",
    email: "rohan.iyer@apple.com",
    device: "Windows 11 Home",
    agentVersion: "1.0.0",
    avatar: RohanIyer,
    details: {
      os: "Windows 11 Pro 23H2",
      loggedIn: "rohani",
      deviceName: "ROHAN-PC",
      domain: "WorkGroup",
      manufacturer: "Asus",
      publicIP: "198.51.100.200",
      privateIP: "192.168.1.120",
      hardware: {
        cpu: {
          name: "AMD Ryzen 7 5800X",
          manufacturer: "AMD",
          speed: "3.80 GHz",
          cores: 8,
        },
        gpu: {
          name: "NVIDIA RTX 3070",
          manufacturer: "NVIDIA",
          capacity: "8 GB",
        },
        memory: {
          name: "G.Skill Trident Z",
          manufacturer: "G.Skill",
          speed: "3600 MHz",
          capacity: "32 GB",
        },
        storage: {
          name: "Samsung 980 Pro NVMe",
          manufacturer: "Samsung",
          capacity: "2 TB",
        },
      },
    },
  },
];
