export const connections = [
  {
    key: "1",
    date: "02/04/2025",
    name: "Carson Darrin",
    initials: "JD",
    email: "carson.darrin@apple.com",
    device: "Windows 10 Pro",
    agentVersion: "1.0.0",
  },
  {
    key: "2",
    date: "08/04/2025",
    name: "Franz Perez",
    initials: "FP",
    email: "franz.perez@apple.com",
    device: "Windows 10 Home",
    agentVersion: "1.0.0",
  },
  {
    key: "3",
    date: "14/04/2025",
    name: "Aditya Mehra",
    initials: "AM",
    email: "aditya.mehra@apple.com",
    device: "Windows 11 Home",
    agentVersion: "1.0.0",
  },
  {
    key: "4",
    date: "18/04/2025",
    name: "Neha Kulkarni",
    initials: "NK",
    email: "neha.kulkarni@apple.com",
    device: "Windows 10",
    agentVersion: "1.0.0",
  },
  {
    key: "5",
    date: "25/04/2025",
    name: "Rohan Iyer",
    initials: "RI",
    email: "rohan.iyer@apple.com",
    device: "Windows 11 Home",
    agentVersion: "1.0.0",
  },
];
