export const devices = [
  {
    key: "1",
    empId: "EMP-001",
    name: "Carson Darrin",
    initials: "JD",
    email: "carson.darrin@apple.com",
    tags: ["Administrator"],
    description: "Windows 10 Pro",
  },
  {
    key: "2",
    empId: "EMP-002",
    name: "Franz Perez",
    initials: "FP",
    email: "franz.perez@apple.com",
    tags: ["Developer"],
    description: "Windows 10 Home",
  },
  {
    key: "3",
    empId: "EMP-003",
    name: "Aditya Mehra",
    initials: "AM",
    email: "aditya.mehra@secureu.in",
    tags: ["CEO"],
    description: "Windows 11 Home",
  },
  {
    key: "4",
    empId: "EMP-004",
    name: "Neha Kulkarni",
    initials: "NK",
    email: "neha.kulkarni@secureu.in",
    tags: ["Intern"],
    description: "Windows 11 Home",
  },
  {
    key: "5",
    empId: "EMP-005",
    name: "Rohan Iyer",
    initials: "RI",
    email: "rohan.iyer@secureu.in",
    tags: ["Assistant"],
    description: "Windows 11 Home",
  },
];
